name: ml-pruning
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch=2.1.2
  - torchvision=0.16.1
  - pytorch-cuda=12.1
  - hydra-core=1.3.2
  - wandb=0.18.1
  - timm=0.9.16
  - scipy=1.13.1
  - pandas=2.2.2
  - numpy=1.26.4
  - pip:
    - transformers
    - torchmetrics
    - torch-pruning