# https://hydra.cc/docs/configure_hydra/intro/

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}/${run_id}
sweep:
  dir: ${paths.log_dir}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}/${run_id}
  subdir: ${hydra.job.num}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/out.log